apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    tier: db
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    type: ClusterIp           # nodePort / loadBalancer
  selector:
    tier: db
