apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    tier: database
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30001          # ranges between 30000 to 32767
  # protocol: TCP            # optional
  type: ClusterIp            # or nodePort / loadBalancer
  selector:
    tier: db                 # must be same like pods label which we desire to attach to 
