apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deploy
  name: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: front-end
  template:
    metadata:
      labels:
        app: my-deploy
        tier: front-end
    spec:
      containers:
      - image: nginx
        name: nginxpod
