# Taints are applied on Nodes
# accordingly the pod applied with same toleration as tain on node will place pod on node
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: bee
  name: bee
spec:
  containers:
  - image: nginx
    name: bee
    resources: {}
  tolerations:
  - key: spray
    value: mortein
    operator: Equal
    effect: NoSchedule
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
