apiVersion: v1
kind: Pod
metadata:
  name: elephant
  namespace: default
spec:
  containers:
  - image: polinux/stress
    imagePullPolicy: Always
    name: mem-stress
    resources:
      limits:
        cpu: "2"
        memory: 20Mi
      requests:
        cpu: "1.5"
        memory: 5Mi
