apiVersion: v1
kind: Pod
metadata:
  name: ubuntupod
  namespace: default
spec:
  containers:
  - image: ubuntu
    name: ubuntucontainer
    resources:
      limits:
        cpu: "2"                          # max cpu value is used by pod. can't go over the limit specified
        memory: 20Mi                      # max cpu memory used by pod. can go over the limit specified but exits pod if over goes with OOM failed error
      requests:
        cpu: "0.5"                        # by default min cpu value is reserved. where 1 cpu = 1000m cpu and 0.5=500m cpu
        memory: 5Mi                       # by default min memory is reserved 
