apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany                        # ReadOnlyMany / ReadWriteOnce / ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:                                # awsElasticBlockStore:
    path: /pv/log                          # volueme 
